// <auto-generated />
using System;
using BaseCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseCore.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517164047_AddAdvancedOrders")]
    partial class AddAdvancedOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseCore.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and fashion items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books and publications",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home and garden products",
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports equipment and accessories",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Description = "May tinh bang",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tai nghe va thiet bi am thanh",
                            Name = "Tai nghe"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Smartwatch",
                            Name = "Dong ho thong minh"
                        },
                        new
                        {
                            Id = 9,
                            Description = "May anh va camera",
                            Name = "May anh"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("District")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ExpectedPickupTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("InvoiceCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InvoiceEmail")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("InvoiceRequired")
                        .HasColumnType("bit");

                    b.Property<string>("InvoiceTaxCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("ProductDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ShippingDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StorePickupLocation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ward")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasFilter("[OrderCode] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderCancellation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCancellations");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SelectedVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialOrImei")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTimelines");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscounted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresSerialTracking")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Slug")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarrantyMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 17, 16, 40, 46, 495, DateTimeKind.Utc).AddTicks(7617),
                            Description = "High-performance laptop",
                            ImageUrl = "",
                            IsActive = true,
                            IsBestSeller = false,
                            IsDiscounted = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Name = "Laptop Dell XPS 15",
                            Price = 35000000m,
                            RequiresSerialTracking = false,
                            Stock = 10,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 17, 16, 40, 46, 495, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Latest Apple smartphone",
                            ImageUrl = "",
                            IsActive = true,
                            IsBestSeller = false,
                            IsDiscounted = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Name = "iPhone 15 Pro",
                            Price = 28000000m,
                            RequiresSerialTracking = false,
                            Stock = 15,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 17, 16, 40, 46, 495, DateTimeKind.Utc).AddTicks(7683),
                            Description = "Comfortable cotton t-shirt",
                            ImageUrl = "",
                            IsActive = true,
                            IsBestSeller = false,
                            IsDiscounted = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Name = "T-Shirt Cotton",
                            Price = 250000m,
                            RequiresSerialTracking = false,
                            Stock = 100,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 17, 16, 40, 46, 495, DateTimeKind.Utc).AddTicks(7686),
                            Description = "Learn programming basics",
                            ImageUrl = "",
                            IsActive = true,
                            IsBestSeller = false,
                            IsDiscounted = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Name = "Programming Book",
                            Price = 450000m,
                            RequiresSerialTracking = false,
                            Stock = 50,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 17, 16, 40, 46, 495, DateTimeKind.Utc).AddTicks(7688),
                            Description = "Complete gardening toolkit",
                            ImageUrl = "",
                            IsActive = true,
                            IsBestSeller = false,
                            IsDiscounted = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Name = "Garden Tools Set",
                            Price = 850000m,
                            RequiresSerialTracking = false,
                            Stock = 25,
                            WarrantyMonths = 12
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedProductId");

                    b.HasIndex("ProductId", "RecommendedProductId", "Type")
                        .IsUnique();

                    b.ToTable("ProductRecommendations");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductSpecValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SpecDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValueText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SpecDefinitionId");

                    b.HasIndex("ProductId", "SpecDefinitionId")
                        .IsUnique();

                    b.ToTable("ProductSpecValues");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ColorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Storage")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariantName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("BaseCore.Entities.SpecDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("text");

                    b.Property<bool>("IsComparable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Code")
                        .IsUnique();

                    b.ToTable("SpecDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "screenSize",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kích thước màn hình",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "screenTechnology",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Công nghệ màn hình",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "rearCamera",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Camera sau",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Code = "frontCamera",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Camera trước",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Code = "chipset",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Chipset",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Code = "ram",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "RAM",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Code = "internalStorage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Bộ nhớ trong",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Code = "battery",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Pin",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Code = "os",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Hệ điều hành",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Code = "cpuType",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Loại CPU",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Code = "ram",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Dung lượng RAM",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Code = "hardDrive",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Ổ cứng",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Code = "graphicsCard",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Card đồ họa",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Code = "screenSize",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kích thước màn hình",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Code = "screenResolution",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Độ phân giải màn hình",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Code = "battery",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Pin",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Code = "os",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Hệ điều hành",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Code = "screenSize",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kích thước màn hình",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Code = "chipset",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Chipset",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            Code = "ram",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "RAM",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Code = "internalStorage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Bộ nhớ trong",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Code = "battery",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Pin",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Code = "frontCamera",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Camera trước",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Code = "rearCamera",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Camera sau",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Code = "headphoneType",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Loại tai nghe",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Code = "audioTechnology",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Công nghệ âm thanh",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Code = "microphone",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Micro",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            Code = "connection",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kết nối",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            Code = "batteryLife",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Thời lượng pin",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            Code = "noiseCancellation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Chống ồn",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            Code = "screenTechnology",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Công nghệ màn hình",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            Code = "screenSize",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kích thước màn hình",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 8,
                            Code = "calling",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Nghe gọi",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 8,
                            Code = "healthFeatures",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Tiện ích sức khỏe",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 8,
                            Code = "batteryLife",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Thời lượng pin",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            Code = "waterResistance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Chống nước",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            Code = "cameraLine",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Dòng camera",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            Code = "resolution",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Độ phân giải",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            Code = "lensAngle",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Góc ống kính",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 9,
                            Code = "stabilization",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Chống rung",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            Code = "wirelessConnection",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "text",
                            IsComparable = true,
                            IsFilterable = false,
                            IsRequired = false,
                            Name = "Kết nối không dây",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderCancellation", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany("Cancellations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderTimeline", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany("Timelines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductImage", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductRecommendation", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("Recommendations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Product", "RecommendedProduct")
                        .WithMany()
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RecommendedProduct");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductSpecValue", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("SpecValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.SpecDefinition", "SpecDefinition")
                        .WithMany("ProductSpecValues")
                        .HasForeignKey("SpecDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SpecDefinition");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductVariant", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaseCore.Entities.SpecDefinition", b =>
                {
                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Navigation("Cancellations");

                    b.Navigation("OrderDetails");

                    b.Navigation("Timelines");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Recommendations");

                    b.Navigation("SpecValues");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("BaseCore.Entities.SpecDefinition", b =>
                {
                    b.Navigation("ProductSpecValues");
                });
#pragma warning restore 612, 618
        }
    }
}
