[package]
name = "TechStoreRustService"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiberius = { version = "0.12.3", features = ["tokio", "tokio-util", "chrono", "rust_decimal"] }
tokio-util = { version = "0.7", features = ["compat"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
